"""Public-host adapter: course RPC, reconnecting loopback tunnels, own Nginx."""
import base64
import hashlib
import json
import http.client
from pathlib import Path
import re
import shlex
import socket
import ssl
import subprocess
import time
import urllib.parse

from .common import atomic_json, atomic_text, instance
from .course import check_health
from .supervisor import Supervisor


class Runtime:
    def __init__(self, config):
        self.config = config
        self.root = Path(config["root"]).resolve()
        self.supervisor = Supervisor(self.root / "tunnels", self.root / "control-venv/bin/python")

    def ssh(self):
        return ["ssh", "-T", "-i", self.config["course_key"], "-p", str(self.config["course_ssh_port"]),
                "-o", "BatchMode=yes", "-o", "StrictHostKeyChecking=yes",
                "-o", f"UserKnownHostsFile={self.config['known_hosts']}",
                "-o", "ConnectTimeout=10", "-o", "ServerAliveInterval=15",
                "-o", "ServerAliveCountMax=3", "-o", "ExitOnForwardFailure=yes"]

    def rpc(self, request):
        remote = f"{self.config['course_user']}@{self.config['course_host']}"
        result = subprocess.run(self.ssh() + [remote], input=json.dumps(request),
                                text=True, capture_output=True, timeout=780)
        if result.returncode:
            raise RuntimeError(f"course RPC failed: {result.stdout[-2000:]} {result.stderr[-1000:]}")
        return json.loads(result.stdout)

    def tunnel_port(self, port):
        return port + 10000

    def port_available(self, port):
        with socket.socket() as sock:
            try:
                sock.bind(("127.0.0.1", self.tunnel_port(port)))
            except OSError:
                return False
        return self.rpc({"op": "port_available", "port": port})["available"]

    def ensure(self, ident, commit, port, bundle):
        instance(ident)
        request = {"op": "ensure", "instance": ident, "sha": commit, "port": port}
        if bundle is not None:
            request.update(bundle=base64.b64encode(bundle).decode(), digest=hashlib.sha256(bundle).hexdigest())
        self.rpc(request)
        remote = f"{self.config['course_user']}@{self.config['course_host']}"
        command = self.ssh() + ["-N", "-L", f"127.0.0.1:{self.tunnel_port(port)}:127.0.0.1:{port}", remote]
        self.supervisor.configure(ident, shlex.join(command), self.root)
        self.health(port)

    def health(self, port):
        check_health(self.tunnel_port(port))

    def remove(self, ident, port):
        instance(ident)
        # Don't release the allocation when the course host is unreachable.
        self.rpc({"op": "remove", "instance": ident})
        self.supervisor.remove(ident)

    def publish(self, routes):
        gateway = self.root / "gateway"
        blocks = []
        for prefix, row in sorted(routes.items()):
            if row.get('kind') == 'web':
                from .web import build_id, environment
                build_id(row['build_id'])
                environment(row['config']['environment'])
                if not re.fullmatch('[0-9a-f]{32}', row['deployment']):
                    raise ValueError('invalid web deployment')
                web_root = self.root / 'web'
                config_path = web_root / 'deployments' / row['deployment'] / 'runtime-config.json'
                atomic_json(config_path, row['config'])
                html_path = web_root / 'builds' / row['build_id'] / 'index.html'
                if not html_path.is_file():
                    raise ValueError('web build files are missing')
                blocks.append(f'location = {prefix[:-1]} {{ return 308 {prefix}; }}')
                for suffix, path, mime in [('', html_path, 'text/html'), ('index.html', html_path, 'text/html'),
                                           ('runtime-config.json', config_path, 'application/json')]:
                    blocks.append(f'''location = {prefix}{suffix} {{
    alias {path};
    default_type {mime};
    add_header Cache-Control no-store always;
    add_header X-Livelife-Frontend-SHA {row['config']['frontend_sha']} always;
}}''')
                continue
            instance(row["id"])
            # All prefixes are generated by Registry, not user-provided URLs.
            if prefix not in ("/api/staging/",) and not prefix.startswith(("/api/pr-", "/api/versions/be-")):
                raise ValueError("invalid route prefix")
            blocks.append(f"""location ^~ {prefix} {{
    limit_req zone=livelife_api burst=20 nodelay;
    proxy_pass http://127.0.0.1:{self.tunnel_port(row['port'])}/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Authorization "";
    proxy_hide_header X-Livelife-Backend-SHA;
    add_header X-Livelife-Backend-SHA {row['sha']} always;
    add_header Cache-Control no-store always;
    proxy_read_timeout 30s;
}}
""")
        routes_path = gateway / "config/routes.conf"
        previous = routes_path.read_text() if routes_path.exists() else ""
        candidate = "\n".join(blocks)
        atomic_text(routes_path, candidate)
        command = ["/usr/sbin/nginx", "-p", str(gateway) + "/", "-c", str(gateway / "nginx.conf")]
        try:
            # nginx -t attempts to bind listen sockets. The manager has no
            # low-port capability; validate an otherwise identical config on
            # a loopback high port, then signal the systemd-owned master.
            with socket.socket() as sock:
                sock.bind(("127.0.0.1", 0))
                check_port = sock.getsockname()[1]
            config = (gateway / "nginx.conf").read_text()
            if config.count("listen 443 ssl;") != 1:
                raise ValueError("gateway must have exactly one managed HTTPS listener")
            config = config.replace("listen 443 ssl;", f"listen 127.0.0.1:{check_port} ssl;")
            config = config.replace("include config/routes.conf;", f"include {routes_path};")
            check_path = gateway / "data/check.conf"
            atomic_text(check_path, config)
            check_command = command[:-1] + [str(check_path), "-t"]
            subprocess.run(check_command, capture_output=True, check=True, timeout=15)
            subprocess.run(command + ["-s", "reload"], capture_output=True, check=True, timeout=15)
            for prefix, row in routes.items():
                if row.get('kind') == 'web':
                    self.check_web_route(prefix, row['config'])
        except Exception:
            atomic_text(routes_path, previous)
            raise
        atomic_json(gateway / "data/versions.json", {prefix: (row['config'] if row.get('kind') == 'web' else
                                                {"instance": row["id"], "backend_sha": row["sha"]})
                                                for prefix, row in routes.items()})

    def check_web_route(self, prefix, config):
        host = urllib.parse.urlparse(self.config['base_url']).hostname
        credentials = (self.root / 'credentials/access.txt').read_text().strip()
        authorization = 'Basic ' + base64.b64encode(credentials.encode()).decode()
        deadline = time.monotonic() + 5
        while True:
            connection = http.client.HTTPConnection(host, timeout=10)
            connection.sock = ssl.create_default_context().wrap_socket(
                socket.create_connection(('127.0.0.1', 443), timeout=10), server_hostname=host)
            try:
                connection.request('GET', prefix, headers={'Authorization': authorization})
                response = connection.getresponse()
                response.read()
                valid = response.status == 200 and response.getheader('X-Livelife-Frontend-SHA') == config['frontend_sha']
                connection.request('GET', prefix + 'runtime-config.json', headers={'Authorization': authorization})
                response = connection.getresponse()
                body = response.read()
                valid = valid and response.status == 200 and json.loads(body) == config
            except (ValueError, OSError):
                valid = False
            finally:
                connection.close()
            if valid:
                return
            if time.monotonic() >= deadline:
                raise RuntimeError('web HTTPS verification failed: ' + prefix)
            time.sleep(0.1)
